### ISSUE TITLE
Package name conflict with Django ImageKit

### ISSUE THREAD

**Issue by vstoykov** [imagekit-developer/python-sdk-demo#1]
Hello guys,

I saw your package in PyPi https://pypi.python.org/pypi/imagekit and I just wanted to note you that `imagekit` conflicts with the top level package provided from `django-imagekit`.

This can have some bad consequences for people which try to have both apps installed in the same environment. Here is the issue in Django ImageKit https://github.com/matthewwithanm/django-imagekit/issues/401

It's up to you guys ti decide if you want or not to rename the toplevel package. I just wanted to mention it because saw that you are still in Beta state.

Regards,
Venelin Stoykov

**Comment by cloudmeteor** [comment]
Thanks for pointing it out. We have released new package with name imagekitio for our future updates. We are not sure about the old package. We might remove it in future.

Regards,
Somesh
