### ISSUE TITLE
ConnectionError: Failed to establish a new connection: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by aswinckr** [imagekit-developer/python-sdk-demo#2]
Im getting this error when i try and run your application

`ConnectionError: HTTPConnectionPool(host='dev-upload.imagekit.io', port=80): Max retries exceeded with url: /rest/api/image/highcampers (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x105fca650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
`

(ofcourse i have added my own api key. The dashboard has public and private key .. is that the same api key and secret key? )

**Comment by cloudmeteor** [comment]
@aswinckr Your Keys are okay. I have submitted a fix. Update the package and try it again. 

`pip install --upgrade imagekit`

Let me know if this fixes your issue.

**Comment by aswinckr** [comment]
Hi @cloudmeteor . Yes it worked, thanks so much! may i know what was the issue?

**Comment by cloudmeteor** [comment]
It was a config issue from our side.
